return {
	{
		Name = "Chocolate",
		Price = 6,
		Description = "Clássico da casa. Feito com chocolate belga.",
		Icon = "rbxassetid://133019450521137",
	},
	{
		Name = "Baunilha",
		Price = 8,
		Description = "Feito com baunilha importada.",
		Icon = "rbxassetid://123144463380897",
	},
	{
		Name = "Frutas Vermelhas",
		Price = 10,
		Description = "Massa de framboesa com creme de morango e mirtilo.",
		Icon = "rbxassetid://97626631295438",
	},
}